name: Build Installers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pkg
        run: npm install -g pkg

      - name: Install Electron Builder
        run: npm install -g electron-builder

      - name: Set execution permissions (Linux/macOS only)
        if: runner.os != 'Windows'
        run: chmod +x ./build.ps1

      - name: Install appimagetool (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y appimagetool

      - name: Run build script
        shell: pwsh
        run: ./build.ps1

      - name: Upload dist files
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.os }}
          path: dist/
