name: Build CCD Tunnel Helper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set dynamic build version
        shell: bash
        run: |
          DATE=$(date +'%Y%m%d')
          echo "BUILD_VERSION=1.0.0+build.${DATE}.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build app
        run: npm run build -- -c.extraMetadata.version=$BUILD_VERSION
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/
